-- ============================================================
-- 03_schema.sql
-- Connect as: &VECTOR_DEMO_USER
--
-- 벡터 검색 대상 테이블 생성.
--   - embedding : cohere.embed-v4.0 default 1536-dim
--                  (256/512/1024 로 줄이려면 OCI_GENAI_DIM 과 함께 컬럼 차원도 변경)
--
-- 멱등성: 테이블/컬럼/인덱스 모두 존재 여부 확인 후 skip
--
-- DEFINE: &OCI_GENAI_DIM
-- ============================================================
set serveroutput on
set echo on
set define on
whenever sqlerror exit sql.sqlcode

prompt -- 1) 테이블 생성 (없을 때만)
declare
  l_cnt number;
begin
  select count(*) into l_cnt
    from user_tables where table_name = 'DOC_CHUNKS';
  if l_cnt = 0 then
    execute immediate
      'create table doc_chunks (' ||
      '  id         number generated by default as identity primary key,' ||
      '  title      varchar2(200)  not null,' ||
      '  content    varchar2(4000) not null,' ||
      '  embedding  vector(&OCI_GENAI_DIM, float32),' ||
      '  created_at timestamp default systimestamp not null' ||
      ')';
    dbms_output.put_line('table DOC_CHUNKS created with embedding VECTOR(&OCI_GENAI_DIM, float32)');
  else
    dbms_output.put_line('table DOC_CHUNKS already exists - skip');
  end if;
end;
/

prompt -- 2) (안전망) 신규 컬럼이 누락된 기존 테이블이면 ADD
declare
  l_cnt number;
begin
  select count(*) into l_cnt from user_tab_columns
   where table_name = 'DOC_CHUNKS' and column_name = 'EMBEDDING';
  if l_cnt = 0 then
    execute immediate 'alter table doc_chunks add (embedding vector(&OCI_GENAI_DIM, float32))';
    dbms_output.put_line('added column: embedding VECTOR(&OCI_GENAI_DIM, float32)');
  end if;
end;
/

prompt -- 3) 벡터 인덱스는 04_seed 적재 후 생성 (빈 테이블에 거는 것 보다 안정적)

prompt -- 4) 메타 확인
column table_name  format a14
column column_name format a14
column data_type   format a35
column nullable    format a8
select table_name, column_name, data_type, nullable
  from user_tab_columns
 where table_name = 'DOC_CHUNKS'
 order by column_id;

prompt -- 03_schema done
exit
