-- ============================================================
-- 03_schema.sql
-- Connect as: &VECTOR_DEMO_USER
--
-- 벡터 검색 대상 테이블 생성. 동일 content 에 대해 두 가지 OCI GenAI Cohere
-- 모델의 임베딩을 나란히 저장하여 모델 비교가 가능하도록 함.
--   - embedding_v3 : cohere.embed-multilingual-v3.0  (1024-dim, fixed)
--   - embedding_v4 : cohere.embed-v4.0               (가변차원 — 기본 1024,
--                                                     truncation 으로 256/512/1536 도 가능)
--
-- 멱등성: 테이블/컬럼/인덱스 모두 존재 여부 확인 후 skip
-- ============================================================
set serveroutput on
set echo on
set define on
whenever sqlerror exit sql.sqlcode

prompt -- 1) 테이블 생성 (없을 때만)
declare
  l_cnt number;
begin
  select count(*) into l_cnt
    from user_tables where table_name = 'DOC_CHUNKS';
  if l_cnt = 0 then
    execute immediate q'[
      create table doc_chunks (
        id            number generated by default as identity primary key,
        title         varchar2(200)  not null,
        content       varchar2(4000) not null,
        embedding_v3  vector(1024, float32),
        embedding_v4  vector(*,    float32),
        created_at    timestamp default systimestamp not null
      )
    ]';
    dbms_output.put_line('table DOC_CHUNKS created');
  else
    dbms_output.put_line('table DOC_CHUNKS already exists - skip');
  end if;
end;
/

prompt -- 2) (안전망) 신규 컬럼이 누락된 기존 테이블이면 ADD
declare
  procedure ensure_col(p_col varchar2, p_def varchar2) is
    l_cnt number;
  begin
    select count(*) into l_cnt from user_tab_columns
     where table_name = 'DOC_CHUNKS' and column_name = upper(p_col);
    if l_cnt = 0 then
      execute immediate 'alter table doc_chunks add (' || p_col || ' ' || p_def || ')';
      dbms_output.put_line('added column: ' || p_col);
    end if;
  end;
begin
  ensure_col('embedding_v3', 'vector(1024, float32)');
  ensure_col('embedding_v4', 'vector(*, float32)');
end;
/

prompt -- 3) 벡터 인덱스는 04_seed 적재 후 생성 (빈 테이블에 거는 것 보다 안정적)

prompt -- 4) 메타 확인
column table_name  format a14
column column_name format a14
column data_type   format a35
column nullable    format a8
select table_name, column_name, data_type, nullable
  from user_tab_columns
 where table_name = 'DOC_CHUNKS'
 order by column_id;

prompt -- 03_schema done
exit
