-- ============================================================
-- 03_schema.sql
-- Connect as: &VECTOR_DEMO_USER
--
-- 벡터 검색 대상 테이블 생성.
--   - id        : 문서 PK
--   - title     : 짧은 제목
--   - content   : 본문 (검색 대상 텍스트)
--   - embedding : VECTOR(384, FLOAT32)  ← all-MiniLM-L6-v2 출력 차원
--   - created_at: 적재 시각
--
-- 멱등성: 테이블 이미 있으면 skip
-- ============================================================
set serveroutput on
set echo on
set define on
whenever sqlerror exit sql.sqlcode

prompt -- 1) 테이블 생성 (없을 때만)
declare
  l_cnt number;
begin
  select count(*) into l_cnt
    from user_tables where table_name = 'DOC_CHUNKS';
  if l_cnt = 0 then
    execute immediate q'[
      create table doc_chunks (
        id          number generated by default as identity primary key,
        title       varchar2(200)  not null,
        content     varchar2(4000) not null,
        embedding   vector(384, float32),
        created_at  timestamp default systimestamp not null
      )
    ]';
    dbms_output.put_line('table DOC_CHUNKS created');
  else
    dbms_output.put_line('table DOC_CHUNKS already exists - skip');
  end if;
end;
/

prompt -- 2) 벡터 인덱스 (IVF — 소규모 데이터에 충분, HNSW 보다 빌드 빠름)
declare
  l_cnt number;
begin
  select count(*) into l_cnt
    from user_indexes where index_name = 'DOC_CHUNKS_EMB_IDX';
  if l_cnt = 0 then
    execute immediate q'[
      create vector index doc_chunks_emb_idx
        on doc_chunks (embedding)
        organization neighbor partitions
        distance cosine
        with target accuracy 95
    ]';
    dbms_output.put_line('vector index DOC_CHUNKS_EMB_IDX created');
  else
    dbms_output.put_line('vector index already exists - skip');
  end if;
exception
  when others then
    -- 데이터가 0건이면 인덱스 생성이 실패할 수 있음 → seed 후 재시도 가능
    dbms_output.put_line('vector index creation deferred: ' || sqlerrm);
end;
/

prompt -- 3) 메타 확인
column table_name format a18
column column_name format a18
column data_type format a30
select table_name, column_name, data_type
  from user_tab_columns
 where table_name = 'DOC_CHUNKS'
 order by column_id;

prompt -- 03_schema done
exit
